### ISSUE TITLE
求教大佬相关强化学习的链接有推荐吗

### ISSUE THREAD

**Issue by 17702513221** [yeyupiaoling/ReinforcementLearning#1]
比如大佬的项目有相关介绍链接吗

**Comment by yeyupiaoling** [comment]
这有个超级马里奥的游戏，用的是PPO，地址：https://github.com/uvipen/Super-mario-bros-PPO-pytorch

**Comment by 17702513221** [comment]
谢谢大佬，点赞大佬的博客
